source "https://rubygems.org"

gem "jets", "~> 4.0.4"

# Include jetpacker if you are building html pages
gem "jetpacker"
gem "sqlite3"
gem "revise_auth-jets", path: "../../../revise_auth-jets"
# Include pg gem if you are using ActiveRecord, remove next line
# and config/database.yml file if you are not
gem "pg"

gem "dynomite"
gem "zeitwerk", ">= 2.5.0"

# development and test groups are not bundled as part of the deployment
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "shotgun"
  gem "rack"
  gem "puma"
end

group :test do
  gem "rspec" # rspec test group only or we get the "irb: warn: can't alias context from irb_context warning" when starting jets console
  gem "launchy"
  gem "capybara"
  gem "minitest"
end
