name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
          rubygems: latest

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        env:
          DATABASE_URL: "sqlite3:revise_auth_test"
          RAILS_ENV: test
        run: |
          cd spec/dummy
          bundle install
          JETS_ENV=test jets db:create db:migrate
          bundle exec rspec
